CREATE TABLE Customer (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	department_id BIGINT,
	version INT
);

CREATE TABLE Department (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	version INT
);

create sequence customer_sequence start with 1 increment by 1;
create sequence department_sequence start with 1 increment by 1;

insert into Customer (first_name, last_name, version) values ('Jack', 'Bauer', 0);
insert into Customer (first_name, last_name, version) values ('Chloe', 'O Brian', 0);
insert into Customer (first_name, last_name, version) values ('Kim', 'Bauer', 0);
insert into Customer (first_name, last_name, version) values ('David', 'Palmer', 0);
insert into Customer (first_name, last_name, version) values ('Michelle', 'Dessler', 0);